import { readFileSync } from "node:fs";
import { PublicKey, SYSVAR_SLOT_HASHES_PUBKEY } from "@solana/web3.js";
import { describe, expect, it } from "vitest";
import { ARENA_PROGRAM_ID, ArenaProgram, arenaErrorName, decodeEntry, decodeTournament, TOKEN_PROGRAM_ID } from "../src/chain/arena-program";
import { fromHex, toHex } from "../src/chain/tournament";

/** Generated by the Rust program: roguelike/program/programs/dungeon-arena/src/fixtures.rs */
const fx = JSON.parse(readFileSync(new URL("./fixtures/arena-program.json", import.meta.url), "utf8"));
const I = fx.instructions;
const key = (n: number) => new PublicKey(new Uint8Array(32).fill(n));
const program = new ArenaProgram();
const token = { mint: key(2) };

describe("arena program client", () => {
  it("targets the program id the program declares", () => {
    expect(ARENA_PROGRAM_ID.toBase58()).toBe(fx.programId);
  });

  it("encodes every instruction exactly like the program", () => {
    const a = I.createTournament.args;
    const t = key(9);
    const cases: [string, Uint8Array][] = [
      [
        "createTournament",
        program.createTournament(key(1), token, {
          id: a.id,
          rulesVersion: a.rulesVersion,
          seedSlot: BigInt(a.seedSlot),
          secretCommitment: fromHex(a.secretCommitment),
          entryFee: BigInt(a.entryFee),
          attemptsPerEntry: a.attemptsPerEntry,
          endTs: BigInt(a.endTs),
          revealDeadlineTs: BigInt(a.revealDeadlineTs),
          rakeBps: a.rakeBps,
          payoutBps: a.payoutBps,
        }).data,
      ],
      ["fund", program.fund(key(4), t, token, key(5), BigInt(I.fund.amount)).data],
      ["enter", program.enter(key(4), t, token, key(5)).data],
      ["recordSlotHash", program.recordSlotHash(t).data],
      ["submitResult", program.submitResult(key(1), t, key(4), BigInt(I.submitResult.score), fromHex(I.submitResult.replayHash)).data],
      ["reveal", program.reveal(key(1), t, fromHex(I.reveal.secret)).data],
      ["finalize", program.finalize(t, token, key(5)).data],
      ["claim", program.claim(key(4), t, token, key(5)).data],
      ["cancel", program.cancel(key(4), t).data],
      ["refund", program.refund(key(4), t, token, key(5)).data],
      ["withdraw", program.withdraw(key(1), t, token, key(5)).data],
    ];
    expect(cases.map(([name]) => name).sort()).toEqual(Object.keys(I).sort());
    for (const [name, data] of cases) expect(toHex(data), name).toBe(I[name].data);
  });

  it("decodes tournament and entry accounts", () => {
    const t = decodeTournament(fromHex(fx.accounts.tournament.data));
    expect(fromHex(fx.accounts.tournament.data).length).toBeLessThanOrEqual(fx.accounts.tournament.space);
    expect(t.authority.equals(key(1))).toBe(true);
    expect(t.mint.equals(key(2))).toBe(true);
    expect(t.id).toBe("2026-10-01");
    expect(t.seedSlot).toBe(123_456_789n);
    expect(t.slotHashRecorded).toBe(true);
    expect(t.recordedSlot).toBe(123_456_791n);
    expect(toHex(t.slotHash)).toBe("33".repeat(32));
    expect(t.revealed).toBe(true);
    expect(toHex(t.secret)).toBe("07".repeat(32));
    expect(t.entryFee).toBe(1_000_000n);
    expect(t.attemptsPerEntry).toBe(3);
    expect(t.endTs).toBe(1_790_000_000n);
    expect(t.payoutBps).toEqual([6000, 3000, 1000, 0, 0]);
    expect(t.status).toBe("finalized");
    expect(t.entries).toBe(7);
    expect(t.prizePool).toBe(12_350_000n);
    expect(t.leaderboard.map((p) => [p.player.toBase58(), Number(p.score), Number(p.slot)])).toEqual(fx.accounts.tournament.leaderboard);
    expect(t.bump).toBe(254);

    const e = decodeEntry(fromHex(fx.accounts.entry.data));
    expect(e.player.equals(key(21))).toBe(true);
    expect(e).toMatchObject({ attemptsUsed: 2, hasScore: true, bestScore: 900n, claimed: true, refunded: false, bump: 253 });
    expect(toHex(e.bestReplayHash)).toBe("5a".repeat(32));
    expect(() => decodeTournament(fromHex(fx.accounts.entry.data))).toThrow();
  });

  it("derives the same PDAs as the program", () => {
    const p = fx.pdas;
    const tournament = program.tournamentAddress(new PublicKey(p.authority), p.id);
    expect(tournament.toBase58()).toBe(p.tournament);
    expect(program.vaultAddress(tournament).toBase58()).toBe(p.vault);
    expect(program.entryAddress(tournament, new PublicKey(p.player)).toBase58()).toBe(p.entry);
  });

  it("lists accounts in the order the program expects", () => {
    const t = key(9);
    const submit = program.submitResult(key(1), t, key(4), 1n, new Uint8Array(32));
    expect(submit.keys.map((k) => [k.pubkey.toBase58(), k.isSigner, k.isWritable])).toEqual([
      [key(1).toBase58(), true, false],
      [t.toBase58(), false, true],
      [program.entryAddress(t, key(4)).toBase58(), false, true],
    ]);
    const record = program.recordSlotHash(t);
    expect(record.keys[1].pubkey.equals(SYSVAR_SLOT_HASHES_PUBKEY)).toBe(true);
    const enter = program.enter(key(4), t, token, key(5));
    expect(enter.keys[6].pubkey.equals(TOKEN_PROGRAM_ID)).toBe(true);
    expect(() => program.reveal(key(1), t, new Uint8Array(31))).toThrow();
  });

  it("names program errors", () => {
    expect(arenaErrorName(6000)).toBe("BadId");
    expect(arenaErrorName(6015)).toBe("NoAttemptsLeft");
    expect(arenaErrorName(7000)).toBeUndefined();
  });
});
