/**
 * TypeScript client for the dungeon-arena Solana program (roguelike/program): instruction
 * encoding, account decoding and PDA addresses. tests/arena-program.test.ts checks every
 * encoding against fixtures generated by the program itself.
 */
import { PublicKey, SYSVAR_SLOT_HASHES_PUBKEY, SystemProgram, TransactionInstruction, type AccountMeta } from "@solana/web3.js";

export const ARENA_PROGRAM_ID = new PublicKey("2v5bvVWahuuibFqe9byqwJAVbUynx6EifhWKJwHsPvpE");
export const TOKEN_PROGRAM_ID = new PublicKey("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA");
export const ASSOCIATED_TOKEN_PROGRAM_ID = new PublicKey("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL");
export const MAX_PLACES = 5;
/** Seconds after the end during which results may still be submitted (SUBMIT_GRACE_SECS). */
export const SUBMIT_GRACE_SECS = 15 * 60;

/** Anchor discriminators: first 8 bytes of sha256("global:<instruction>") and sha256("account:<Name>"). */
const IX = {
  createTournament: "9e89e9e74984bf44",
  fund: "dabc6fdd9871ae07",
  enter: "8b31d172585b4d86",
  recordSlotHash: "481a6265fe73f18c",
  submitResult: "f02a59b40aef09d6",
  reveal: "09233bbea7f94c73",
  finalize: "ab3dda387f730cd9",
  claim: "3ec6d6c1d59f6cd2",
  cancel: "e8dbdf29dbecdcbe",
  refund: "0260b7fb3fd02e2e",
  withdraw: "b712469c946da122",
} as const;
const ACCOUNT = { tournament: "af8b77f273c2395c", entry: "3f129871d7f6ddfa" } as const;

/** ArenaError variants in declaration order; custom error code = 6000 + index. */
export const ARENA_ERRORS = [
  "BadId", "SeedSlotNotInFuture", "BadSchedule", "BadPayout", "RakeTooHigh", "NoAttempts", "NotOpen",
  "EntriesClosed", "OrganizerCannotEnter", "SlotHashAlreadyRecorded", "SeedSlotNotReached", "SeedSlotTooOld",
  "MalformedSlotHashes", "SlotHashNotRecorded", "SubmissionsClosed", "NoAttemptsLeft", "TooEarlyToReveal",
  "AlreadyRevealed", "SecretMismatch", "NotRevealed", "NotFinalized", "NoPrize", "AlreadyClaimed",
  "CannotCancelYet", "NotCancelled", "AlreadyRefunded", "Overflow",
] as const;

export function arenaErrorName(code: number): string | undefined {
  return ARENA_ERRORS[code - 6000];
}

export interface CreateTournamentArgs {
  id: string;
  rulesVersion: number;
  seedSlot: bigint;
  secretCommitment: Uint8Array;
  entryFee: bigint;
  attemptsPerEntry: number;
  endTs: bigint;
  revealDeadlineTs: bigint;
  rakeBps: number;
  payoutBps: number[];
}

export type TournamentStatus = "open" | "finalized" | "cancelled";

export interface Place {
  player: PublicKey;
  score: bigint;
  slot: bigint;
}

export interface TournamentAccount {
  authority: PublicKey;
  mint: PublicKey;
  vault: PublicKey;
  id: string;
  rulesVersion: number;
  seedSlot: bigint;
  secretCommitment: Uint8Array;
  slotHashRecorded: boolean;
  recordedSlot: bigint;
  slotHash: Uint8Array;
  revealed: boolean;
  secret: Uint8Array;
  entryFee: bigint;
  attemptsPerEntry: number;
  endTs: bigint;
  revealDeadlineTs: bigint;
  rakeBps: number;
  payoutBps: number[];
  status: TournamentStatus;
  entries: number;
  unrefundedEntries: number;
  prizePool: bigint;
  placesFilled: number;
  /** Filled places only, best first. */
  leaderboard: Place[];
  bump: number;
}

export interface EntryAccount {
  tournament: PublicKey;
  player: PublicKey;
  attemptsUsed: number;
  hasScore: boolean;
  bestScore: bigint;
  bestReplayHash: Uint8Array;
  claimed: boolean;
  refunded: boolean;
  bump: number;
}

// ---------------------------------------------------------------- borsh

function hexBytes(hex: string): number[] {
  return Array.from(hex.match(/../g)!, (h) => parseInt(h, 16));
}

class Writer {
  private readonly out: number[];
  constructor(discriminator: string) {
    this.out = hexBytes(discriminator);
  }
  u8(v: number): this {
    this.out.push(v & 0xff);
    return this;
  }
  u16(v: number): this {
    return this.int(BigInt(v), 2);
  }
  u64(v: bigint): this {
    return this.int(BigInt.asUintN(64, v), 8);
  }
  i64(v: bigint): this {
    return this.int(BigInt.asUintN(64, v), 8);
  }
  bytes(b: Uint8Array, length?: number): this {
    if (length !== undefined && b.length !== length) throw new Error(`ожидалось ${length} байт, получено ${b.length}`);
    this.out.push(...b);
    return this;
  }
  str(s: string): this {
    const b = new TextEncoder().encode(s);
    this.int(BigInt(b.length), 4);
    return this.bytes(b);
  }
  done(): Buffer {
    return Buffer.from(this.out);
  }
  private int(v: bigint, size: number): this {
    for (let i = 0; i < size; i++) this.out.push(Number((v >> BigInt(8 * i)) & 0xffn));
    return this;
  }
}

class Reader {
  private at = 0;
  constructor(private readonly data: Uint8Array) {}
  private take(n: number): Uint8Array {
    if (this.at + n > this.data.length) throw new Error("данные аккаунта обрываются");
    const out = this.data.subarray(this.at, this.at + n);
    this.at += n;
    return out;
  }
  private int(size: number): bigint {
    const b = this.take(size);
    let v = 0n;
    for (let i = size - 1; i >= 0; i--) v = (v << 8n) | BigInt(b[i]);
    return v;
  }
  u8 = () => Number(this.int(1));
  bool = () => this.u8() !== 0;
  u16 = () => Number(this.int(2));
  u32 = () => Number(this.int(4));
  u64 = () => this.int(8);
  i64 = () => BigInt.asIntN(64, this.int(8));
  bytes = (n: number) => Uint8Array.from(this.take(n));
  pubkey = () => new PublicKey(this.take(32));
  str = () => new TextDecoder().decode(this.take(this.u32()));
  discriminator(expected: string): void {
    const got = Array.from(this.take(8), (b) => b.toString(16).padStart(2, "0")).join("");
    if (got !== expected) throw new Error("это не аккаунт ожидаемого типа");
  }
}

// ---------------------------------------------------------------- accounts

const STATUSES: TournamentStatus[] = ["open", "finalized", "cancelled"];

export function decodeTournament(data: Uint8Array): TournamentAccount {
  const r = new Reader(data);
  r.discriminator(ACCOUNT.tournament);
  const t = {
    authority: r.pubkey(),
    mint: r.pubkey(),
    vault: r.pubkey(),
    id: r.str(),
    rulesVersion: r.u16(),
    seedSlot: r.u64(),
    secretCommitment: r.bytes(32),
    slotHashRecorded: r.bool(),
    recordedSlot: r.u64(),
    slotHash: r.bytes(32),
    revealed: r.bool(),
    secret: r.bytes(32),
    entryFee: r.u64(),
    attemptsPerEntry: r.u8(),
    endTs: r.i64(),
    revealDeadlineTs: r.i64(),
    rakeBps: r.u16(),
    payoutBps: Array.from({ length: MAX_PLACES }, () => r.u16()),
    status: STATUSES[r.u8()],
    entries: r.u32(),
    unrefundedEntries: r.u32(),
    prizePool: r.u64(),
    placesFilled: r.u8(),
  };
  const board = Array.from({ length: MAX_PLACES }, () => ({ player: r.pubkey(), score: r.u64(), slot: r.u64() }));
  return { ...t, leaderboard: board.slice(0, t.placesFilled), bump: r.u8() };
}

export function decodeEntry(data: Uint8Array): EntryAccount {
  const r = new Reader(data);
  r.discriminator(ACCOUNT.entry);
  return {
    tournament: r.pubkey(),
    player: r.pubkey(),
    attemptsUsed: r.u8(),
    hasScore: r.bool(),
    bestScore: r.u64(),
    bestReplayHash: r.bytes(32),
    claimed: r.bool(),
    refunded: r.bool(),
    bump: r.u8(),
  };
}

// ---------------------------------------------------------------- instructions

const writable = (pubkey: PublicKey, isSigner = false): AccountMeta => ({ pubkey, isSigner, isWritable: true });
const readonly = (pubkey: PublicKey, isSigner = false): AccountMeta => ({ pubkey, isSigner, isWritable: false });

export interface TokenContext {
  mint: PublicKey;
  /** SPL Token or Token-2022. */
  tokenProgram?: PublicKey;
}

/** Instruction builders and addresses for one deployment of the program. */
export class ArenaProgram {
  constructor(readonly programId: PublicKey = ARENA_PROGRAM_ID) {}

  tournamentAddress(authority: PublicKey, id: string): PublicKey {
    return PublicKey.findProgramAddressSync([Buffer.from("tournament"), authority.toBuffer(), Buffer.from(id)], this.programId)[0];
  }

  vaultAddress(tournament: PublicKey): PublicKey {
    return PublicKey.findProgramAddressSync([Buffer.from("vault"), tournament.toBuffer()], this.programId)[0];
  }

  entryAddress(tournament: PublicKey, player: PublicKey): PublicKey {
    return PublicKey.findProgramAddressSync([Buffer.from("entry"), tournament.toBuffer(), player.toBuffer()], this.programId)[0];
  }

  private ix(keys: AccountMeta[], data: Buffer): TransactionInstruction {
    return new TransactionInstruction({ programId: this.programId, keys, data });
  }

  createTournament(authority: PublicKey, token: TokenContext, a: CreateTournamentArgs): TransactionInstruction {
    if (a.payoutBps.length !== MAX_PLACES) throw new Error(`нужно ${MAX_PLACES} долей призов`);
    const w = new Writer(IX.createTournament)
      .str(a.id)
      .u16(a.rulesVersion)
      .u64(a.seedSlot)
      .bytes(a.secretCommitment, 32)
      .u64(a.entryFee)
      .u8(a.attemptsPerEntry)
      .i64(a.endTs)
      .i64(a.revealDeadlineTs)
      .u16(a.rakeBps);
    for (const b of a.payoutBps) w.u16(b);
    const tournament = this.tournamentAddress(authority, a.id);
    return this.ix(
      [
        writable(authority, true),
        writable(tournament),
        readonly(token.mint),
        writable(this.vaultAddress(tournament)),
        readonly(token.tokenProgram ?? TOKEN_PROGRAM_ID),
        readonly(SystemProgram.programId),
      ],
      w.done(),
    );
  }

  fund(funder: PublicKey, tournament: PublicKey, token: TokenContext, funderToken: PublicKey, amount: bigint): TransactionInstruction {
    return this.ix(
      [
        readonly(funder, true),
        readonly(tournament),
        readonly(token.mint),
        writable(this.vaultAddress(tournament)),
        writable(funderToken),
        readonly(token.tokenProgram ?? TOKEN_PROGRAM_ID),
      ],
      new Writer(IX.fund).u64(amount).done(),
    );
  }

  enter(player: PublicKey, tournament: PublicKey, token: TokenContext, playerToken: PublicKey): TransactionInstruction {
    return this.ix(
      [
        writable(player, true),
        writable(tournament),
        writable(this.entryAddress(tournament, player)),
        readonly(token.mint),
        writable(this.vaultAddress(tournament)),
        writable(playerToken),
        readonly(token.tokenProgram ?? TOKEN_PROGRAM_ID),
        readonly(SystemProgram.programId),
      ],
      new Writer(IX.enter).done(),
    );
  }

  recordSlotHash(tournament: PublicKey): TransactionInstruction {
    return this.ix([writable(tournament), readonly(SYSVAR_SLOT_HASHES_PUBKEY)], new Writer(IX.recordSlotHash).done());
  }

  submitResult(authority: PublicKey, tournament: PublicKey, player: PublicKey, score: bigint, replayHash: Uint8Array): TransactionInstruction {
    return this.ix(
      [readonly(authority, true), writable(tournament), writable(this.entryAddress(tournament, player))],
      new Writer(IX.submitResult).u64(score).bytes(replayHash, 32).done(),
    );
  }

  reveal(authority: PublicKey, tournament: PublicKey, secret: Uint8Array): TransactionInstruction {
    return this.ix([readonly(authority, true), writable(tournament)], new Writer(IX.reveal).bytes(secret, 32).done());
  }

  /** Permissionless; `authorityToken` must be a token account of the organizer for the mint. */
  finalize(tournament: PublicKey, token: TokenContext, authorityToken: PublicKey): TransactionInstruction {
    return this.ix(
      [
        writable(tournament),
        readonly(token.mint),
        writable(this.vaultAddress(tournament)),
        writable(authorityToken),
        readonly(token.tokenProgram ?? TOKEN_PROGRAM_ID),
      ],
      new Writer(IX.finalize).done(),
    );
  }

  claim(player: PublicKey, tournament: PublicKey, token: TokenContext, playerToken: PublicKey): TransactionInstruction {
    return this.payout(IX.claim, player, tournament, token, playerToken);
  }

  refund(player: PublicKey, tournament: PublicKey, token: TokenContext, playerToken: PublicKey): TransactionInstruction {
    return this.payout(IX.refund, player, tournament, token, playerToken);
  }

  cancel(caller: PublicKey, tournament: PublicKey): TransactionInstruction {
    return this.ix([readonly(caller, true), writable(tournament)], new Writer(IX.cancel).done());
  }

  withdraw(authority: PublicKey, tournament: PublicKey, token: TokenContext, authorityToken: PublicKey): TransactionInstruction {
    return this.ix(
      [
        readonly(authority, true),
        readonly(tournament),
        readonly(token.mint),
        writable(this.vaultAddress(tournament)),
        writable(authorityToken),
        readonly(token.tokenProgram ?? TOKEN_PROGRAM_ID),
      ],
      new Writer(IX.withdraw).done(),
    );
  }

  private payout(disc: string, player: PublicKey, tournament: PublicKey, token: TokenContext, playerToken: PublicKey): TransactionInstruction {
    return this.ix(
      [
        readonly(player, true),
        writable(tournament),
        writable(this.entryAddress(tournament, player)),
        readonly(token.mint),
        writable(this.vaultAddress(tournament)),
        writable(playerToken),
        readonly(token.tokenProgram ?? TOKEN_PROGRAM_ID),
      ],
      new Writer(disc).done(),
    );
  }
}

/** Associated token account of `owner` for `mint`. */
export function associatedTokenAddress(owner: PublicKey, mint: PublicKey, tokenProgram: PublicKey = TOKEN_PROGRAM_ID): PublicKey {
  return PublicKey.findProgramAddressSync([owner.toBuffer(), tokenProgram.toBuffer(), mint.toBuffer()], ASSOCIATED_TOKEN_PROGRAM_ID)[0];
}

/** Creates `owner`'s associated token account for `mint` unless it already exists. */
export function createAssociatedTokenAccountIdempotent(
  payer: PublicKey,
  owner: PublicKey,
  mint: PublicKey,
  tokenProgram: PublicKey = TOKEN_PROGRAM_ID,
): TransactionInstruction {
  return new TransactionInstruction({
    programId: ASSOCIATED_TOKEN_PROGRAM_ID,
    keys: [
      writable(payer, true),
      writable(associatedTokenAddress(owner, mint, tokenProgram)),
      readonly(owner),
      readonly(mint),
      readonly(SystemProgram.programId),
      readonly(tokenProgram),
    ],
    data: Buffer.from([1]),
  });
}

/** Decimals of an SPL (or Token-2022) mint: mint authority option (36) + supply (8) come first. */
export function mintDecimals(data: Uint8Array): number {
  if (data.length < 45) throw new Error("это не аккаунт токена");
  return data[44];
}
